parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  sourceType: module
  extraFileExtensions:
    - .js
plugins:
  - '@typescript-eslint/eslint-plugin'
  - simple-import-sort
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
root: true
env:
  node: true
  jest: true
rules:
  simple-import-sort/imports: 'error'
  simple-import-sort/exports: 'error'
